Repository cartesi/image-kernel, pull requests merged in 2023-10, with the labels that each got.

#30 feat: add a checksum to released files
  .github/workflows/main.yml
Labels: enhancement, good first issue

#32 Replace MTD flash drives with PMEM drives
  configs/default-linux-config
Labels: enhancement

#36 Release v0.18.0
  CHANGELOG.md
  Makefile
Labels: enhancement

#38 ci: set kernel timestamp when building
  .github/workflows/main.yml
  Makefile
Labels: bug
